name: honggfuzz
run-name: honggfuzz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
      - uses: actions/checkout@v4
        with:
          repository: libunwind/libunwind
          ref: 'b3ca1b59a795a617877c01fe5d299ab7a07ff29d'
      - name: check ndk path
        run: |
          ls -al $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      
      - name: configure libunwind
        run: |
          set -x
          autoreconf -i
          mkdir build
          cd build
          ../configure --build=aarch64-linux-gnu
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          CC: $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          CXX: $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
          CFLAGS: "-I$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -g -Wall -Wextra"
          CXXFLAGS: "-I$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -g -Wall -Wextra"
          LDFLAGS: -L$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot
      - name: build libunwind
        run: |
          make -C build -j
      # - uses: actions/setup-go@v5.2.0
      #   with:
      #     go-version: 1.22
      # - name: Build the build tool
      #   run: 'pwd && go mod tidy && cd cmd/build && go build .'
      # - name: check build config
      #   run: 'pwd && cat .github/config/main.config.yaml'
      # - name: Build AndroidBox
      #   run: 'pwd && cmd/build/build -f .github/config/main.config.yaml -t ${{ github.ref_name }}'
      # - name: Create Release
      #   uses: ncipollo/release-action@v1.15.0
      #   with:
      #     artifacts: cmd/AndroidBox/AndroidBox_*,cmd/build/build
  