name: honggfuzz
run-name: honggfuzz

on:
  workflow_dispatch:

jobs:
  build-libunwind:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          repository: libunwind/libunwind
          ref: 'b3ca1b59a795a617877c01fe5d299ab7a07ff29d'

      - name: configure libunwind
        run: |
          sudo apt update
          sudo apt install -y g++-13-aarch64-linux-gnu abigail-tools
          mkdir -p /home/runner/work/honggfuzz-build/honggfuzz-build/dist
          set -x
          autoreconf -i
          mkdir build
          cd build
          ../configure --build=aarch64-linux-gnu --host=aarch64-linux-gnu --prefix=/home/runner/work/honggfuzz-build/honggfuzz-build/dist
        env:
          CC: gcc-13
          CXX: g++-13
          CFLAGS: "-O3 -g -Wall -Wextra"
          CXXFLAGS: "-O3 -g -Wall -Wextra"
          LDFLAGS: -O3
      - name: build libunwind
        run: |
          make -C build -j
          make -C build install
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: libunwind
          path: /home/runner/work/honggfuzz-build/honggfuzz-build/dist
  build-capstone:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          repository: capstone-engine/capstone
          ref: 'e710e4fcf40302c25d7bdc28da93571a61f21f5d'
      - name: build
        run: |
          sudo apt update
          sudo apt install -y g++-13-aarch64-linux-gnu abigail-tools cmake
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          mkdir -p /home/runner/work/honggfuzz-build/honggfuzz-build/dist
          cmake --build build
          cmake --install build --prefix /home/runner/work/honggfuzz-build/honggfuzz-build/dist
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: capstone
          path: /home/runner/work/honggfuzz-build/honggfuzz-build/dist
  build-honggfuzz:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: google/honggfuzz
          ref: '02f8a7f572e8a98aaffcb5b3d5c73a2835770dcf'
      - uses: actions/download-artifact@v4
        with:
          path: /home/runner/work/honggfuzz-build/honggfuzz-build/
      - name: setup
        run: |
          sudo mv /home/runner/work/honggfuzz-build/honggfuzz-build/libunwind/include/* /usr/local/include/
          sudo mv /home/runner/work/honggfuzz-build/honggfuzz-build/capstone/include/* /usr/local/include/
          sudo mv /home/runner/work/honggfuzz-build/honggfuzz-build/libunwind/lib/* /usr/lib/
          sudo mv /home/runner/work/honggfuzz-build/honggfuzz-build/capstone/lib/* /usr/lib/
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
      - name: build
        run: |
          make android-all
  