name: honggfuzz
run-name: honggfuzz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      # - uses: nttld/setup-ndk@v1
      #   id: setup-ndk
      #   with:
      #     ndk-version: r26d
      # - name: check ndk path
      #   run: |
      #     ls -al $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/
      #   env:
      #     ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      
      - uses: actions/checkout@v4
        with:
          repository: libunwind/libunwind
          ref: 'b3ca1b59a795a617877c01fe5d299ab7a07ff29d'

      - name: configure libunwind
        run: |
          sudo apt update
          sudo apt install -y g++-13-aarch64-linux-gnu abigail-tools
          mkdir -p /home/runner/work/honggfuzz-build/honggfuzz-build/dist
          set -x
          autoreconf -i
          mkdir build
          cd build
          ../configure --build=aarch64-linux-gnu --host=aarch64-linux-gnu --enable-debug --prefix=/home/runner/work/honggfuzz-build/honggfuzz-build/dist
        env:
          CC: gcc-13
          CXX: g++-13
          CFLAGS: "-O3 -g -Wall -Wextra"
          CXXFLAGS: "-O3 -g -Wall -Wextra"
          LDFLAGS: -O3
      - name: build libunwind
        run: |
          make -C build -j
          make install
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          path: /home/runner/work/honggfuzz-build/honggfuzz-build/dist
      # - uses: actions/setup-go@v5.2.0
      #   with:
      #     go-version: 1.22
      # - name: Build the build tool
      #   run: 'pwd && go mod tidy && cd cmd/build && go build .'
      # - name: check build config
      #   run: 'pwd && cat .github/config/main.config.yaml'
      # - name: Build AndroidBox
      #   run: 'pwd && cmd/build/build -f .github/config/main.config.yaml -t ${{ github.ref_name }}'
      # - name: Create Release
      #   uses: ncipollo/release-action@v1.15.0
      #   with:
      #     artifacts: cmd/AndroidBox/AndroidBox_*,cmd/build/build
  